DROP DATABASE IF EXISTS DB;
CREATE DATABASE DB;

USE DB;

CREATE TABLE IF NOT EXISTS NotificheUWP(
  `ID` int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `URL` text NOT NULL,
  `Registration` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;